# Page defaults
base_url    = "https://jakublesko.com"
title       = "Jakub LeÅ¡ko"
description = "Blog about programming and technology in general"

# Enable RSS feed generation
generate_feed = true
feed_filename = "rss.xml"

# Make rendered HTML a bit smaller
minify_html = false

[markdown]
# Enable syntax highlighting
highlight_code  = true
highlight_theme = "visual-studio-dark"

# Enable emoji rendering (:smile: becomes ðŸ˜„)
render_emoji = true

# Open external links in a new tab
external_links_target_blank = true

# Privacy enhancements for external links
external_links_no_follow    = true
external_links_no_referrer  = true
